# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 629434bae1a4918c1dbf24b174b152b88d275108906b69ffad834ee9dab2500a83e43740b041f4bd05abd4b5d65dade8eb93545b59052ada4b7bf85c0207a8d8

test:
  secret_key_base: a260141e13a34c4bbb681bb9671ad167d1ffcb87a86278cc2d58dae628b2a9846b682cc7bb54a0e56a5f4ed7be920a1b8de09be839b2cb512e03b2378dc35073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
